#ifdef __INTELLISENSE__
// There is an issue with Intellisense not
// finding unity_config.h, which is autogenerated
// by PlatformIO? Ignore the error reporting for
// a moment.
#pragma diag_suppress 1696
#endif

#include <unity.h>

#ifdef __INTELLISENSE__
// ...and disable the suppression again.
#pragma diag_default 1696
#endif
