// DO NOT MODIFY THIS FILE
// This file is auto-generated by `scripts/embed_web.py`
// To modify this file, edit the respective source file.

#pragma once

#include <Arduino.h>

namespace assets {

const char CSS_INDEX_CSS[] PROGMEM = R"rawliteral(
* {
    font-family: sans-serif;
    box-sizing: border-box;
}

body {
    margin: 0;
    min-height: 100vh;
    background: #151515;
    color: #fff;

    display: flex;
    align-items: center;
    justify-content: center;
    padding: 24px;
}

.panel {
    border: 1px solid red;
    width: 100%;
    max-width: 430px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 15px;
}

.light-on-off-panel {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    gap: 24px;
    border: 1px solid red;
    width: 100%;
}

h1 {
    font-size: 30px;
    margin: 0 0 30px;
    text-align: center;
    font-weight: 600;
}

button {
    display: block;
    width: 100%;
    height: 76px;

    border: none;
    border-radius: 18px;

    font-size: 21px;
    font-weight: 600;

    background: #303030;
    color: white;

    -webkit-tap-highlight-color: transparent;
}

button:active {
    transform: scale(0.98);
    background: #444;
}

.light-on {
    background: #e4c45c;
    color: #111;
}

#status {
    margin-top: 25px;
    height: 24px;
    text-align: center;
    color: #999;
    font-size: 14px;
}
)rawliteral";

}
