// DO NOT MODIFY THIS FILE
// This file is auto-generated by `scripts/embed_web.py`
// To modify this file, edit the respective source file.

#pragma once

#include <Arduino.h>

namespace assets {

const char CSS_INDEX_CSS[] PROGMEM = R"rawliteral(
* {
    font-family: sans-serif;
    box-sizing: border-box;
}

body {
    margin: 0;
    min-height: 100vh;
    background: #151515;
    color: #fff;

    display: flex;
    align-items: center;
    justify-content: center;
    padding: 24px;
}

.fa-regular {
    font-family: 'Font Awesome 7 Free';
    font-weight: 400;
    font-style: normal;
    display: inline-block;
    line-height: 1;
}

.fa-solid {
    font-family: 'Font Awesome 7 Free';
    font-weight: 900;
    font-style: normal;
    display: inline-block;
    line-height: 1;
}

.panel {
    width: 100%;
    max-width: 430px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 24px;
}

.light-on-off-panel {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    gap: 24px;
    width: 100%;
}

h1 {
    font-size: 30px;
    margin: 0 0 30px;
    text-align: center;
    font-weight: 600;
}

.button-icon {
    margin-right: 12px;
}

button {
    display: block;
    width: 100%;
    height: 76px;

    border: none;
    border-radius: 18px;

    font-size: 21px;
    font-weight: 600;

    background: #303030;
    color: white;
    filter: brightness(1);

    -webkit-tap-highlight-color: transparent;
}

button:active {
    transform: scale(0.98);
    transition: 0.1s ease, fill 0.1s ease;
    filter: brightness(1.2);
}

.fan-btn {
    fill: #303030;
    filter: brightness(1);
    -webkit-tap-highlight-color: transparent;
    transform-box: fill-box;
    transform-origin: center;

    -webkit-user-select: none;
    -ms-user-select: none;
    user-select: none;
}

.fan-btn .fan-btn-shape {
    fill: #2A3A54;
    transition: fill 0.1s ease;
}

.fan-btn .fan-btn-label {
    fill: white;
    font-size: 7px;
    font-weight: 600;
    font-family: sans-serif;
    text-anchor: middle;
    dominant-baseline: central;
    pointer-events: none; 
}

.fan-btn-label .fa-icon {
    font-family: "Font Awesome 7 Free";
    font-weight: 900;
    font-size: 12px;
}

.fan-btn:active {
    transform: scale(0.98);
    filter: brightness(1.2);
    transition: 0.1s ease, fill 0.1s ease;
}

.light-on {
    background: #e4c45c;
    color: #111;
}

#status {
    height: 24px;
    text-align: center;
    color: #999;
    font-size: 14px;
}
)rawliteral";

}
