// DO NOT MODIFY THIS FILE
// This file is auto-generated by `scripts/embed_web.py`
// To modify this file, edit the respective source file.

#pragma once

#include <Arduino.h>

namespace assets {

const char INDEX_HTML[] PROGMEM = R"rawliteral(
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
    <meta name="theme-color" content="#151515">

    <title>Ceiling Fan</title>

    <link rel="stylesheet" href="css/index.css">
    <link rel="stylesheet" href="css/regular.min.css">
    <link rel="stylesheet" href="css/solid.min.css">
    <link rel="stylesheet" href="css/fontawesome.min.css">
    <script src="index.js" lang="javascript"></script>
</head>

<body>
    <div class="panel">
        <h1>Ceiling Fan</h1>
        <div class="light-on-off-panel">
            <button class="off" onclick="sendCommand('/api/light/off')">
                Light Off
            </button>
            <button class="light-on" onclick="sendCommand('/api/light/on')">
                <i class="fa-solid fa-sun"></i>Light On
            </button>
        </div>
        <button class="off" onclick="sendCommand('/api/fan/off')">
            Fan Off
        </button>
        <button class="off" onclick="sendCommand('/api/fan/1')">
            Fan 1
        </button>
        <button class="off" onclick="sendCommand('/api/fan/3')">
            Fan 3
        </button>
        <button class="off" onclick="sendCommand('/api/fan/6')">
            Fan 6
        </button>
        <div id="status"></div>
    </div>
</body>

</html>
)rawliteral";

}
