// DO NOT MODIFY THIS FILE
// This file is auto-generated by `scripts/embed_web.py`
// To modify this file, edit the respective source file.

#pragma once

#include <Arduino.h>

namespace assets {

const char JS_INDEX_JS[] PROGMEM = R"rawliteral(
async function sendCommand(url) {
    const status =
        document.getElementById('status');
    status.textContent = 'Sending…';

    try {
        const response = await fetch(url, {
            method: 'POST',
            cache: 'no-store'
        });
        const text = await response.text();

        if (response.ok) {
            status.textContent = text;
        } else {
            status.textContent = 'Error: ' + text;
        }
    } catch (e) {
        status.textContent =
            'Connection failed';
    }
}

)rawliteral";

}
