import io
from pathlib import Path

CHUNK_SIZE = 30

# Import and env is provided by platformio
Import("env")  # pyright: ignore[reportUndefinedVariable]

project_dir = Path(
    env.subst("$PROJECT_DIR")  # pyright: ignore[reportUndefinedVariable]
)

assets_dir = project_dir / "web"
assets_target_dir = project_dir / "include" / "web_remote" / "assets"
assets_target_dir.mkdir(parents=True, exist_ok=True)


def ignore_file(path: Path):
    return path.name in ["LICENSE.txt"]


def process_assets():
    for path in assets_dir.rglob("*"):
        if ignore_file(path) or not path.is_file():
            continue

        target_file = assets_target_dir / path.relative_to(assets_dir)
        asset_name = (
            str(path.relative_to(assets_dir))
            .replace("/", "_")
            .replace(".", "_")
            .replace("-", "_")
            .upper()
        )

        target_file.parent.mkdir(parents=True, exist_ok=True)
        embed_file(path, target_file.with_name(path.name + ".h"), asset_name)


def embed_file(source: Path, target: Path, asset_name: str):
    if source.suffix.lower() in [".html", ".css", ".js"]:
        embed_text_file(source, target, asset_name)
    else:
        embed_binary_file(source, target, asset_name)


def write_header(file_stream: io.TextIOWrapper, asset_name: str):
    lines = [
        "// DO NOT MODIFY THIS FILE\n"
        "// This file is auto-generated by `scripts/embed_web.py`\n"
        "// To modify this file, edit the respective source file.\n\n"
        "#pragma once\n\n",
        "#include <Arduino.h>\n\n",
        "namespace assets {\n\n" f'const char {asset_name}[] PROGMEM = R"rawliteral(\n',
    ]
    file_stream.writelines(lines)


def write_footer(file_stream: io.TextIOWrapper):
    file_stream.write('\n)rawliteral";\n\n}\n')


def embed_text_file(source: Path, target: Path, asset_name: str):
    with target.open("w") as f:
        write_header(f, asset_name)
        f.write(source.read_text())
        write_footer(f)


def embed_binary_file(source: Path, target: Path, asset_name: str):
    with target.open("w") as f_out:
        write_header(f_out, asset_name)
        with source.open("rb") as f_in:
            while chunk := f_in.read(CHUNK_SIZE):
                hex_escaped = "".join(f"\\x{b:02x}" for b in chunk)
                f_out.write(f'    "{hex_escaped}"\n')
        write_footer(f_out)


process_assets()
