import io
from pathlib import Path

CHUNK_SIZE = 15

# Import and env is provided by platformio
Import("env")  # pyright: ignore[reportUndefinedVariable]

project_dir = Path(
    env.subst("$PROJECT_DIR")  # pyright: ignore[reportUndefinedVariable]
)

include_dir = project_dir / "include"
assets_target_dir = include_dir / "web_remote" / "assets" / "web"
assets_target_dir.mkdir(parents=True, exist_ok=True)


def ignore_file(path: Path):
    return path.name in [
        "LICENSE.txt",
        "Readme.md",
        ".gitignore",
        "fa-regular-400.woff2",  # only subset is included
        "fa-solid-900.woff2",  # only subset is included
    ]


def guess_mime_from_ending(path: Path) -> str:
    match path.suffix:
        case ".html":
            return "text/html"
        case ".css":
            return "text/css"
        case ".js":
            return "text/javascript"
        case ".svg":
            return "image/svg+xml"
        case ".woff2":
            return "font/woff2"
        case _:
            raise NotImplementedError()


def process_web_assets(assets_dir):
    resources = []

    for path in assets_dir.rglob("*"):
        if ignore_file(path) or not path.is_file():
            continue

        path_in_assets = path.relative_to(assets_dir)

        target_file = assets_target_dir / path_in_assets
        asset_name = (
            str(path_in_assets)
            .replace("/", "_")
            .replace(".", "_")
            .replace("-", "_")
            .upper()
        )

        target_file.parent.mkdir(parents=True, exist_ok=True)
        target_header_file = target_file.with_name(path.name + ".h")
        is_binary = embed_file(path, target_header_file, asset_name)

        resources.append((target_header_file, asset_name, path_in_assets, is_binary))

    with (include_dir / "web_remote/assets/resources.h").open("w") as f:
        lines = [
            "// DO NOT MODIFY THIS FILE\n"
            "// This file is modified by `scripts/embed_web.py`\n\n"
            "#pragma once\n\n"
        ]
        f.writelines(lines)

        for i, _, _, _ in resources:
            i = Path(i).relative_to(include_dir)
            f.write(f"#include <{i}>\n")

        f.write("\n#define WEB_SERVER_REGISTER_STATIC_ASSETS(server)")

        for _, name, path, is_binary in resources:
            mime = guess_mime_from_ending(path)

            len_specifier = f", sizeof(assets::{name})" if is_binary else ""

            if str(path) == "index.html":
                # We assume `index.html` is being served as root document
                f.write(f' \\\n    (server).on("/", HTTP_GET, []() {{ \\\n')
            else:
                f.write(
                    f' \\\n    (server).on("/{path}", HTTP_GET, []() {{ \\\n',
                )

            f.write("        (server).send_P(200, ")
            f.write(f'"{mime}", assets::{name}{len_specifier}); \\\n')
            f.write("    });")
        f.write("\n")


def embed_file(source: Path, target: Path, asset_name: str) -> bool:
    if source.suffix.lower() in [".html", ".css", ".js", ".svg"]:
        embed_text_file(source, target, asset_name)
        return False
    else:
        embed_binary_file(source, target, asset_name)
        return True


def write_header(file_stream: io.TextIOWrapper, asset_name: str):
    lines = [
        "// DO NOT MODIFY THIS FILE\n"
        "// This file is auto-generated by `scripts/embed_web.py`\n"
        "// To modify this file, edit the respective source file.\n\n"
        "#pragma once\n\n",
        "#include <Arduino.h>\n\n",
        "namespace assets {\n\n" f"const char {asset_name}[] PROGMEM = ",
    ]
    file_stream.writelines(lines)


def write_footer(file_stream: io.TextIOWrapper):
    file_stream.write(";\n\n}\n")


def embed_text_file(source: Path, target: Path, asset_name: str):
    with target.open("w") as f:
        write_header(f, asset_name)
        f.write('R"rawliteral(\n')
        f.write(source.read_text())
        f.write('\n)rawliteral"')
        write_footer(f)


def embed_binary_file(source: Path, target: Path, asset_name: str):
    with target.open("w") as f_out:
        write_header(f_out, asset_name)
        with source.open("rb") as f_in:
            end_of_line_char = "{"
            while chunk := f_in.read(CHUNK_SIZE):
                hex_escaped = ", ".join(f"0x{b:02x}" for b in chunk)
                f_out.write(f"{end_of_line_char}\n    {hex_escaped}")
                end_of_line_char = ","
        f_out.write("\n}")
        write_footer(f_out)


process_web_assets(project_dir / "web")
